name: Create HACS Release ZIP

on:
  release:
    types: [published]

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          mkdir -p release
          zip -r release/stateful_scenes.zip custom_components/stateful_scenes

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: release/stateful_scenes.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
