name: Test Latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: '0 12 * * 5'  # Weekly on Fridays at noon

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout the repository"
      uses: actions/checkout@v6

    - name: "Set up Python"
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: "Install latest HA and test plugin (including betas)"
      run: | 
        uv sync
        uv pip install --prerelease=allow --upgrade homeassistant pytest-homeassistant-custom-component


    - name: "Test"
      run: uv run pytest